server:
  port: 8081
  servlet:
    context-path: /psi
    encoding:
      charset: UTF-8
      
spring:
  thymeleaf:
    cache: false
    mode: HTML
    encoding: UTF-8
  datasource:  
    url: jdbc:mysql://localhost:3306/psi3?serverTimezone=UTC&characterEncoding=utf-8&useUnicode=true  
    username: root  
    password: zxcv985613  
    driverClassName: com.mysql.cj.jdbc.Driver  
  jpa:  
    database: MYSQL  
    show-sql: true  
    hibernate:  
      ddl-auto: update  
    properties:  
      hibernate:
        # 8D 版本才可正常運行  
        dialect: org.hibernate.dialect.MySQL8Dialect
        # 支援 Lazy 使用
        enable_lazy_load_no_trans: true
        format_sql: true
